version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork
  configserver:
    depends_on:
      - rabbitmq
    build:
      context: ./ConfigServer
    ports:
      - "8888:8888"
    networks:
      - mynetwork

networks:
  mynetwork: